### ISSUE TITLE
Running aiohttp on uvloop too

### ISSUE THREAD

**Issue by almarklein** [vibora-io/benchmarks#1]
I saw this coming by https://twitter.com/andrew_svetlov/status/1010051495407050754

**Comment by frnkvieira** [comment]
Yes. Instead of being here and doing a pull request the guy prefers to bash a project that exploded while still being developed. Sanic is running under uvloop, I've no intention to let aiohttp out of this and I even explicitly said I'm no expert in every single framework so I need help on this. Anyway, thanks, I'll re-run the benchmarks today and update the results so maybe he calms down a little.

**Comment by almarklein** [comment]
I agree that it was not very fair. He's the main author of aiohttp which might explain the bashing.

BTW he mentioned in another tweet "... use bytes for vibora plain test response but str for aiohttp and others."

**Comment by frnkvieira** [comment]
Fixed.
